### ISSUE TITLE
deprecation findDOMNode in React.StrictMode prevents edit

### ISSUE THREAD

**Issue by lee-chase** [elyra-ai/canvas#1995]
Ref: #3801

When React is run in strict mode the diagrams are not editable.

Reproduce:
Change harness/src/index.js to 

```jsx
  <React.StrictMode>
    <HashRouter>
      <IntlProvider locale='en'>
        <div>
          <Route exact path='/' component={App} />
          <Route exact path='/app-small' component={AppSmall} />
          <Route exact path='/app-tiny' component={AppTiny} />
          <Route path='/properties' component={CommonPropertiesComponents} />
          <Route path='/conditions' component={CommonPropertiesConditions} />
        </div>
      </IntlProvider>
    </HashRouter>
  </React.StrictMode>
```

Note none of the diagrams are editable and the console output

```
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of ResizeDetector which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at ResizeDetector (http://localhost:3001/js/canvasharness.js:166142:28)
    at Toolbar (http://localhost:3001/js/canvasharness.js:380154:86)
    at div
    at CommonCanvasToolbar (http://localhost:3001/js/canvasharness.js:305503:86)
    at injectIntl(CommonCanvasToolbar)
    at ConnectFunction (http://localhost:3001/js/canvasharness.js:493784:68)
    at div
    at div
    at div
    at CommonCanvasCentralItems (http://localhost:3001/js/canvasharness.js:303454:86)
    at ConnectFunction (http://localhost:3001/js/canvasharness.js:493784:68)
    at Provider (http://localhost:3001/js/canvasharness.js:493495:20)
    at CommonCanvas (http://localhost:3001/js/canvasharness.js:307885:86)
    at injectIntl(CommonCanvas)
    at IntlProvider (http://localhost:3001/js/canvasharness.js:492926:47)
    at div
    at App (http://localhost:3001/js/canvasharness.js:385109:86)
    at Route (http://localhost:3001/js/canvasharness.js:496974:29)
    at div
    at IntlProvider (http://localhost:3001/js/canvasharness.js:492926:47)
    at Router (http://localhost:3001/js/canvasharness.js:496603:30)
    at HashRouter (http://localhost:3001/js/canvasharness.js:496256:35)
```

**Comment by tomlyn** [comment]
Warnings have been fixed. Other issues recorded in issue 3801 so closing this one
