### ISSUE TITLE
`validate subtabs work correctly` unit test is failing to run on Travis but success locally

### ISSUE THREAD

**Issue by caritaou** [elyra-ai/canvas#258]
A unit test is failing on Travis in the PR builds. This test runs successfully in our local dev env. We should disable the test for now in Travis to unblock dev. But we need to make sure that this runs successfully in our dev env for all new PRs

```
Summary of all failing tests
 FAIL  __tests__/common-properties/components/editor-form-test.js
  ● tabs and subtabs should be rendered correctly › validate subtabs work correctly

    TypeError: _tab$tabAnchor.scrollIntoView is not a function
      38 | 		const subTabs = subTabsContainer.find("a.bx--tabs__nav-link");
      39 | 		expect(subTabs).to.have.length(3);
    > 40 | 		subTabs.at(2).simulate("click");
         | 		              ^
      41 | 		category = wrapper.find("div[data-id='properties-Primary2']");
      42 | 		// use react object to find tab content.
      43 | 		let tabContent = category.find("div.properties-sub-tab-container TabContent");

      at Tabs.scrollTabIntoView (node_modules/carbon-components-react/lib/components/Tabs/Tabs.js:148:148)
      at Tabs.selectTabAt (node_modules/carbon-components-react/lib/components/Tabs/Tabs.js:163:13)
      at node_modules/carbon-components-react/lib/components/Tabs/Tabs.js:222:15[22m
      at onClick (node_modules/carbon-components-react/lib/components/Tab/Tab.js:104:11)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:336:14)
      at HTMLUnknownElement.callTheUserObjectsOperation (node_modules/jsdom/lib/jsdom/living/generated/EventListener.js:26:30)
      at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:94:17)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:231:34)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:385:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:440:31)
      at invokeGuardedCallbackAndCatchFirstError (node_modules/react-dom/cjs/react-dom.development.js:454:25)
      at executeDispatch (node_modules/react-dom/cjs/react-dom.development.js:584:3)
      at executeDispatchesInOrder (node_modules/react-dom/cjs/react-dom.development.js:609:5)
      at executeDispatchesAndRelease (node_modules/react-dom/cjs/react-dom.development.js:713:5)
      at executeDispatchesAndReleaseTopLevel (node_modules/react-dom/cjs/react-dom.development.js:722:10)
      at forEachAccumulated (node_modules/react-dom/cjs/react-dom.development.js:694:8)
      at runEventsInBatch (node_modules/react-dom/cjs/react-dom.development.js:739:3)
      at node_modules/react-dom/cjs/react-dom-test-utils.development.js:1560:7
      at Object.batchedUpdates$1 [as unstable_batchedUpdates] (node_modules/react-dom/cjs/react-dom.development.js:24386:12)
      at eventFn (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1556:14)
      at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:490:11)
      at node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:354:37
      at batchedUpdates$1 (node_modules/react-dom/cjs/react-dom.development.js:24386:12)
      at Object.act (node_modules/react-dom/cjs/react-dom-test-utils.development.js:1092:14)
      at wrapAct (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:354:13)
      at Object.simulateEvent (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:489:9)
      at ReactWrapper.call (node_modules/enzyme/src/ReactWrapper.js:666:22)
      at ReactWrapper.single (node_modules/enzyme/src/ReactWrapper.js:1170:21)
      at ReactWrapper.simulate (node_modules/enzyme/src/ReactWrapper.js:665:17)
      at Object.<anonymous> (__tests__/common-properties/components/editor-form-test.js:40:17)
Test Suites: 1 failed, 106 passed, 107 total
Tests:       1 failed, 1052 passed, 1053 total
Snapshots:   0 total
Time:        333.169 s
Ran all test suites.
```

**Comment by caritaou** [comment]
Fixed with https://github.com/elyra-ai/canvas/pull/261
